# config/deploy.yml для Telegram Bot
<% require "dotenv"; Dotenv.load(".env") %>
service: music_share_bot
image: <%= ENV.fetch("DOCKER_USERNAME") %>/music_share_bot

primary_role: worker

servers:
  worker:
    hosts:
      - <%= ENV['SERVER_IP'] %>
    proxy: false

registry:
  username: ${DOCKER_USERNAME}
  password: ${KAMAL_REGISTRY_PASSWORD}

env:
  clear:
    TELEGRAM_BOT_TOKEN: <%= ENV['TELEGRAM_BOT_TOKEN'] %>
    MUSIC_SHARE_API_URL: <%= ENV['MUSIC_SHARE_API_URL'] %>
    RACK_ENV: production

ssh:
  user: deploy
  key_data: [<%= ENV['SSH_PRIVATE_KEY'].inspect %>]

builder:
  arch: amd64

